"""Make deleted not nullable and add suspended

Revision ID: 020cc051a254
Revises: 4317c741a539
Create Date: 2023-02-02 08:46:40.510341

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '020cc051a254'
down_revision = '4317c741a539'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account_details', schema='accounts') as batch_op:
        batch_op.add_column(sa.Column('suspended', sa.Boolean(), server_default=sa.text('false'), nullable=False))
        
        # set all values for delete column to false
        op.execute("UPDATE accounts.account_details SET deleted = false WHERE deleted IS NULL")

        batch_op.alter_column('deleted',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               server_default=sa.text('false')
        )        


    with op.batch_alter_table('subreddit_details', schema='subreddits') as batch_op:
        # set all values for delete column to false
        op.execute("UPDATE subreddits.subreddit_details SET deleted = false WHERE deleted IS NULL")
        
        batch_op.alter_column('deleted',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               server_default=sa.text('false')
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subreddit_details', schema='subreddits') as batch_op:
        batch_op.alter_column('deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True
               )

    with op.batch_alter_table('account_details', schema='accounts') as batch_op:
        batch_op.alter_column('deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.drop_column('suspended')

    # ### end Alembic commands ###
