"""empty message

Revision ID: 29268e75844f
Revises: 
Create Date: 2023-02-01 13:49:34.171741

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29268e75844f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('sun_account_id', sa.BigInteger(), nullable=False),
    sa.Column('sun_created_at', sa.DateTime(), server_default=sa.text('(now())'), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('reddit_account_id', sa.Text(), nullable=True),
    sa.Column('created', sa.Float(precision=53), nullable=True),
    sa.Column('created_utc', sa.Float(precision=53), nullable=True),
    sa.PrimaryKeyConstraint('sun_account_id'),
    schema='accounts'
    )
    with op.batch_alter_table('accounts', schema='accounts') as batch_op:
        batch_op.create_index(batch_op.f('ix_accounts_accounts_sun_account_id'), ['sun_account_id'], unique=False)

    op.create_table('subreddits',
    sa.Column('sun_subreddit_id', sa.BigInteger(), nullable=False),
    sa.Column('reddit_subreddit_id', sa.Text(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('sun_created_at', sa.DateTime(), server_default=sa.text('(now())'), nullable=False),
    sa.Column('display_name_prefixed', sa.Text(), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('display_name', sa.Text(), nullable=True),
    sa.Column('created', sa.Float(precision=53), nullable=True),
    sa.Column('lang', sa.Text(), nullable=True),
    sa.Column('created_utc', sa.Float(precision=53), nullable=True),
    sa.Column('path', sa.Text(), nullable=True),
    sa.Column('is_enrolled_in_new_modmail', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('sun_subreddit_id'),
    schema='subreddits'
    )
    with op.batch_alter_table('subreddits', schema='subreddits') as batch_op:
        batch_op.create_index(batch_op.f('ix_subreddits_subreddits_sun_subreddit_id'), ['sun_subreddit_id'], unique=False)

    op.create_table('account_versions',
    sa.Column('sun_account_id', sa.BigInteger(), nullable=False),
    sa.Column('sun_account_version_id', sa.BigInteger(), nullable=False),
    sa.Column('sun_account_detail_id', sa.BigInteger(), nullable=False),
    sa.Column('sun_created_at', sa.DateTime(), server_default=sa.text('(now())'), nullable=False),
    sa.ForeignKeyConstraint(['sun_account_id'], ['accounts.accounts.sun_account_id'], ),
    sa.PrimaryKeyConstraint('sun_account_id', 'sun_account_version_id', 'sun_account_detail_id'),
    sa.UniqueConstraint('sun_account_detail_id'),
    schema='accounts'
    )
    with op.batch_alter_table('account_versions', schema='accounts') as batch_op:
        batch_op.create_index('ix_accounts_account_versions', ['sun_account_id', 'sun_account_version_id', 'sun_account_detail_id'], unique=False)

    op.create_table('posts',
    sa.Column('sun_post_id', sa.BigInteger(), nullable=False),
    sa.Column('sun_subreddit_id', sa.BigInteger(), nullable=False),
    sa.Column('sun_account_id', sa.BigInteger(), nullable=True),
    sa.Column('reddit_post_id', sa.Text(), nullable=False),
    sa.Column('reddit_subreddit_id', sa.Text(), nullable=False),
    sa.Column('reddit_account_id', sa.Text(), nullable=True),
    sa.Column('sun_created_at', sa.DateTime(), server_default=sa.text('(now())'), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('approved_at_utc', sa.Text(), nullable=True),
    sa.Column('permalink', sa.Text(), nullable=True),
    sa.Column('thumbnail_height', sa.BigInteger(), nullable=True),
    sa.Column('author_cakeday', sa.Text(), nullable=True),
    sa.Column('thumbnail_width', sa.BigInteger(), nullable=True),
    sa.Column('author_flair_template_id', sa.Text(), nullable=True),
    sa.Column('is_reddit_media_domain', sa.Boolean(), nullable=True),
    sa.Column('is_created_from_ads_ui', sa.Boolean(), nullable=True),
    sa.Column('post_hint', sa.Text(), nullable=True),
    sa.Column('created', sa.Float(precision=53), nullable=True),
    sa.Column('domain', sa.Text(), nullable=True),
    sa.Column('no_follow', sa.Boolean(), nullable=True),
    sa.Column('created_utc', sa.Float(precision=53), nullable=True),
    sa.Column('is_video', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['sun_account_id'], ['accounts.accounts.sun_account_id'], ),
    sa.ForeignKeyConstraint(['sun_subreddit_id'], ['subreddits.subreddits.sun_subreddit_id'], ),
    sa.PrimaryKeyConstraint('sun_post_id'),
    schema='posts'
    )
    with op.batch_alter_table('posts', schema='posts') as batch_op:
        batch_op.create_index(batch_op.f('ix_posts_posts_sun_post_id'), ['sun_post_id'], unique=False)

    op.create_table('subreddit_versions',
    sa.Column('sun_subreddit_id', sa.BigInteger(), nullable=False),
    sa.Column('sun_subreddit_version_id', sa.BigInteger(), nullable=False),
    sa.Column('sun_subreddit_detail_id', sa.BigInteger(), nullable=False),
    sa.Column('sun_created_at', sa.DateTime(), server_default=sa.text('(now())'), nullable=False),
    sa.ForeignKeyConstraint(['sun_subreddit_id'], ['subreddits.subreddits.sun_subreddit_id'], ),
    sa.PrimaryKeyConstraint('sun_subreddit_id', 'sun_subreddit_version_id', 'sun_subreddit_detail_id'),
    sa.UniqueConstraint('sun_subreddit_detail_id'),
    schema='subreddits'
    )
    with op.batch_alter_table('subreddit_versions', schema='subreddits') as batch_op:
        batch_op.create_index('ix_subreddits_subreddit_versions', ['sun_subreddit_id', 'sun_subreddit_version_id', 'sun_subreddit_detail_id'], unique=False)

    op.create_table('account_details',
    sa.Column('sun_account_detail_id', sa.BigInteger(), nullable=False),
    sa.Column('sun_created_at', sa.DateTime(), server_default=sa.text('(now())'), nullable=False),
    sa.Column('comment_karma', sa.BigInteger(), nullable=True),
    sa.Column('link_karma', sa.BigInteger(), nullable=True),
    sa.Column('total_karma', sa.BigInteger(), nullable=True),
    sa.Column('awardee_karma', sa.BigInteger(), nullable=True),
    sa.Column('awarder_karma', sa.BigInteger(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('listing_use_sort', sa.Boolean(), nullable=True),
    sa.Column('is_employee', sa.Boolean(), nullable=True),
    sa.Column('snoovatar_size', sa.Text(), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=True),
    sa.Column('is_gold', sa.Boolean(), nullable=True),
    sa.Column('icon_img', sa.Text(), nullable=True),
    sa.Column('hide_from_robots', sa.Boolean(), nullable=True),
    sa.Column('pref_show_snoovatar', sa.Boolean(), nullable=True),
    sa.Column('snoovatar_img', sa.Text(), nullable=True),
    sa.Column('accept_followers', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['sun_account_detail_id'], ['accounts.account_versions.sun_account_detail_id'], ),
    sa.PrimaryKeyConstraint('sun_account_detail_id'),
    schema='accounts'
    )
    with op.batch_alter_table('account_details', schema='accounts') as batch_op:
        batch_op.create_index(batch_op.f('ix_accounts_account_details_sun_account_detail_id'), ['sun_account_detail_id'], unique=True)

    op.create_table('comments',
    sa.Column('sun_comment_id', sa.BigInteger(), nullable=False),
    sa.Column('sun_post_id', sa.BigInteger(), nullable=False),
    sa.Column('sun_subreddit_id', sa.BigInteger(), nullable=False),
    sa.Column('sun_account_id', sa.BigInteger(), nullable=True),
    sa.Column('reddit_comment_id', sa.Text(), nullable=False),
    sa.Column('reddit_parent_id', sa.Text(), nullable=True),
    sa.Column('reddit_post_id', sa.Text(), nullable=False),
    sa.Column('reddit_subreddit_id', sa.Text(), nullable=False),
    sa.Column('reddit_account_id', sa.Text(), nullable=True),
    sa.Column('sun_created_at', sa.DateTime(), server_default=sa.text('(now())'), nullable=False),
    sa.Column('created_utc', sa.Numeric(), nullable=True),
    sa.Column('depth', sa.BigInteger(), nullable=True),
    sa.Column('permalink', sa.Text(), nullable=True),
    sa.Column('is_submitter', sa.Boolean(), nullable=True),
    sa.Column('created', sa.Numeric(), nullable=True),
    sa.ForeignKeyConstraint(['sun_account_id'], ['accounts.accounts.sun_account_id'], ),
    sa.ForeignKeyConstraint(['sun_post_id'], ['posts.posts.sun_post_id'], ),
    sa.ForeignKeyConstraint(['sun_subreddit_id'], ['subreddits.subreddits.sun_subreddit_id'], ),
    sa.PrimaryKeyConstraint('sun_comment_id'),
    schema='comments'
    )
    with op.batch_alter_table('comments', schema='comments') as batch_op:
        batch_op.create_index(batch_op.f('ix_comments_comments_sun_comment_id'), ['sun_comment_id'], unique=False)

    op.create_table('post_versions',
    sa.Column('sun_post_id', sa.BigInteger(), nullable=False),
    sa.Column('sun_post_version_id', sa.BigInteger(), nullable=False),
    sa.Column('sun_post_detail_id', sa.BigInteger(), nullable=False),
    sa.Column('sun_created_at', sa.DateTime(), server_default=sa.text('(now())'), nullable=False),
    sa.ForeignKeyConstraint(['sun_post_id'], ['posts.posts.sun_post_id'], ),
    sa.PrimaryKeyConstraint('sun_post_id', 'sun_post_version_id', 'sun_post_detail_id'),
    sa.UniqueConstraint('sun_post_detail_id'),
    schema='posts'
    )
    with op.batch_alter_table('post_versions', schema='posts') as batch_op:
        batch_op.create_index('ix_posts_post_versions', ['sun_post_id', 'sun_post_version_id', 'sun_post_detail_id'], unique=False)

    op.create_table('subreddit_details',
    sa.Column('sun_subreddit_detail_id', sa.BigInteger(), nullable=False),
    sa.Column('sun_created_at', sa.DateTime(), server_default=sa.text('(now())'), nullable=False),
    sa.Column('active_user_count', sa.BigInteger(), nullable=True),
    sa.Column('accounts_active', sa.BigInteger(), nullable=True),
    sa.Column('public_traffic', sa.Boolean(), nullable=True),
    sa.Column('subscribers', sa.BigInteger(), nullable=True),
    sa.Column('subreddit_type', sa.Text(), nullable=True),
    sa.Column('suggested_comment_sort', sa.Text(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('allow_polls', sa.Boolean(), nullable=True),
    sa.Column('collapse_deleted_comments', sa.Boolean(), nullable=True),
    sa.Column('public_description_html', sa.Text(), nullable=True),
    sa.Column('allow_videos', sa.Boolean(), nullable=True),
    sa.Column('allow_discovery', sa.Boolean(), nullable=True),
    sa.Column('accept_followers', sa.Boolean(), nullable=True),
    sa.Column('is_crosspostable_subreddit', sa.Boolean(), nullable=True),
    sa.Column('notification_level', sa.Text(), nullable=True),
    sa.Column('should_show_media_in_comments_setting', sa.Boolean(), nullable=True),
    sa.Column('user_flair_background_color', sa.Text(), nullable=True),
    sa.Column('submit_text_html', sa.Text(), nullable=True),
    sa.Column('restrict_posting', sa.Boolean(), nullable=True),
    sa.Column('free_form_reports', sa.Boolean(), nullable=True),
    sa.Column('wiki_enabled', sa.Boolean(), nullable=True),
    sa.Column('header_img', sa.Text(), nullable=True),
    sa.Column('allow_galleries', sa.Boolean(), nullable=True),
    sa.Column('primary_color', sa.Text(), nullable=True),
    sa.Column('icon_img', sa.Text(), nullable=True),
    sa.Column('quarantine', sa.Boolean(), nullable=True),
    sa.Column('hide_ads', sa.Boolean(), nullable=True),
    sa.Column('prediction_leaderboard_entry_type', sa.Text(), nullable=True),
    sa.Column('emojis_enabled', sa.Boolean(), nullable=True),
    sa.Column('advertiser_category', sa.Text(), nullable=True),
    sa.Column('public_description', sa.Text(), nullable=True),
    sa.Column('comment_score_hide_mins', sa.BigInteger(), nullable=True),
    sa.Column('allow_predictions', sa.Boolean(), nullable=True),
    sa.Column('community_icon', sa.Text(), nullable=True),
    sa.Column('banner_background_image', sa.Text(), nullable=True),
    sa.Column('original_content_tag_enabled', sa.Boolean(), nullable=True),
    sa.Column('community_reviewed', sa.Boolean(), nullable=True),
    sa.Column('submit_text', sa.Text(), nullable=True),
    sa.Column('description_html', sa.Text(), nullable=True),
    sa.Column('spoilers_enabled', sa.Boolean(), nullable=True),
    sa.Column('allow_talks', sa.Boolean(), nullable=True),
    sa.Column('all_original_content', sa.Boolean(), nullable=True),
    sa.Column('has_menu_widget', sa.Boolean(), nullable=True),
    sa.Column('key_color', sa.Text(), nullable=True),
    sa.Column('wls', sa.BigInteger(), nullable=True),
    sa.Column('show_media_preview', sa.Boolean(), nullable=True),
    sa.Column('submission_type', sa.Text(), nullable=True),
    sa.Column('allow_videogifs', sa.Boolean(), nullable=True),
    sa.Column('should_archive_posts', sa.Boolean(), nullable=True),
    sa.Column('can_assign_link_flair', sa.Boolean(), nullable=True),
    sa.Column('accounts_active_is_fuzzed', sa.Boolean(), nullable=True),
    sa.Column('allow_prediction_contributors', sa.Boolean(), nullable=True),
    sa.Column('submit_text_label', sa.Text(), nullable=True),
    sa.Column('link_flair_position', sa.Text(), nullable=True),
    sa.Column('allow_chat_post_creation', sa.Boolean(), nullable=True),
    sa.Column('user_sr_theme_enabled', sa.Boolean(), nullable=True),
    sa.Column('link_flair_enabled', sa.Boolean(), nullable=True),
    sa.Column('disable_contributor_requests', sa.Boolean(), nullable=True),
    sa.Column('banner_img', sa.Text(), nullable=True),
    sa.Column('content_category', sa.Text(), nullable=True),
    sa.Column('banner_background_color', sa.Text(), nullable=True),
    sa.Column('show_media', sa.Boolean(), nullable=True),
    sa.Column('over18', sa.Boolean(), nullable=True),
    sa.Column('header_title', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_chat_post_feature_enabled', sa.Boolean(), nullable=True),
    sa.Column('submit_link_label', sa.Text(), nullable=True),
    sa.Column('restrict_commenting', sa.Boolean(), nullable=True),
    sa.Column('allow_images', sa.Boolean(), nullable=True),
    sa.Column('whitelist_status', sa.Text(), nullable=True),
    sa.Column('mobile_banner_image', sa.Text(), nullable=True),
    sa.Column('allow_predictions_tournament', sa.Boolean(), nullable=True),
    sa.Column('videostream_links_count', sa.Float(precision=53), nullable=True),
    sa.ForeignKeyConstraint(['sun_subreddit_detail_id'], ['subreddits.subreddit_versions.sun_subreddit_detail_id'], ),
    sa.PrimaryKeyConstraint('sun_subreddit_detail_id'),
    schema='subreddits'
    )
    with op.batch_alter_table('subreddit_details', schema='subreddits') as batch_op:
        batch_op.create_index(batch_op.f('ix_subreddits_subreddit_details_sun_subreddit_detail_id'), ['sun_subreddit_detail_id'], unique=False)

    op.create_table('comment_versions',
    sa.Column('sun_comment_id', sa.BigInteger(), nullable=False),
    sa.Column('sun_comment_version_id', sa.BigInteger(), nullable=False),
    sa.Column('sun_comment_detail_id', sa.BigInteger(), nullable=False),
    sa.Column('sun_created_at', sa.DateTime(), server_default=sa.text('(now())'), nullable=False),
    sa.ForeignKeyConstraint(['sun_comment_id'], ['comments.comments.sun_comment_id'], ),
    sa.PrimaryKeyConstraint('sun_comment_id', 'sun_comment_version_id', 'sun_comment_detail_id'),
    sa.UniqueConstraint('sun_comment_detail_id'),
    schema='comments'
    )
    with op.batch_alter_table('comment_versions', schema='comments') as batch_op:
        batch_op.create_index('ix_comments_comment_versions', ['sun_comment_id', 'sun_comment_version_id', 'sun_comment_detail_id'], unique=False)

    op.create_table('post_details',
    sa.Column('sun_post_detail_id', sa.BigInteger(), nullable=False),
    sa.Column('sun_created_at', sa.DateTime(), server_default=sa.text('(now())'), nullable=False),
    sa.Column('gilded', sa.BigInteger(), nullable=True),
    sa.Column('selftext', sa.Text(), nullable=True),
    sa.Column('downs', sa.BigInteger(), nullable=True),
    sa.Column('ups', sa.BigInteger(), nullable=True),
    sa.Column('upvote_ratio', sa.Float(precision=53), nullable=True),
    sa.Column('num_comments', sa.BigInteger(), nullable=True),
    sa.Column('num_reports', sa.Text(), nullable=True),
    sa.Column('removed', sa.Boolean(), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('author_has_subscribed', sa.Boolean(), nullable=True),
    sa.Column('author_is_mod', sa.Boolean(), nullable=True),
    sa.Column('comment_limit', sa.BigInteger(), nullable=True),
    sa.Column('comment_sort', sa.Text(), nullable=True),
    sa.Column('parent_whitelist_status', sa.Text(), nullable=True),
    sa.Column('stickied', sa.Boolean(), nullable=True),
    sa.Column('subreddit_subscribers', sa.BigInteger(), nullable=True),
    sa.Column('num_crossposts', sa.BigInteger(), nullable=True),
    sa.Column('total_awards_received', sa.BigInteger(), nullable=True),
    sa.Column('score', sa.BigInteger(), nullable=True),
    sa.Column('author_premium', sa.Boolean(), nullable=True),
    sa.Column('edited', sa.BigInteger(), nullable=True),
    sa.Column('saved', sa.Boolean(), nullable=True),
    sa.Column('mod_reason_title', sa.Text(), nullable=True),
    sa.Column('clicked', sa.Boolean(), nullable=True),
    sa.Column('hidden', sa.Boolean(), nullable=True),
    sa.Column('pwls', sa.BigInteger(), nullable=True),
    sa.Column('link_flair_css_class', sa.Text(), nullable=True),
    sa.Column('top_awarded_type', sa.Text(), nullable=True),
    sa.Column('hide_score', sa.Boolean(), nullable=True),
    sa.Column('quarantine', sa.Boolean(), nullable=True),
    sa.Column('link_flair_text_color', sa.Text(), nullable=True),
    sa.Column('author_flair_background_color', sa.Text(), nullable=True),
    sa.Column('is_original_content', sa.Boolean(), nullable=True),
    sa.Column('is_meta', sa.Boolean(), nullable=True),
    sa.Column('category', sa.Text(), nullable=True),
    sa.Column('link_flair_text', sa.Text(), nullable=True),
    sa.Column('can_mod_post', sa.Boolean(), nullable=True),
    sa.Column('approved_by', sa.Text(), nullable=True),
    sa.Column('thumbnail', sa.Text(), nullable=True),
    sa.Column('author_flair_css_class', sa.Text(), nullable=True),
    sa.Column('is_self', sa.Boolean(), nullable=True),
    sa.Column('mod_note', sa.Text(), nullable=True),
    sa.Column('link_flair_type', sa.Text(), nullable=True),
    sa.Column('num_duplicates', sa.Integer(), nullable=True),
    sa.Column('wls', sa.BigInteger(), nullable=True),
    sa.Column('removed_by_category', sa.Text(), nullable=True),
    sa.Column('banned_by', sa.Text(), nullable=True),
    sa.Column('author_flair_type', sa.Text(), nullable=True),
    sa.Column('allow_live_comments', sa.Boolean(), nullable=True),
    sa.Column('selftext_html', sa.Text(), nullable=True),
    sa.Column('likes', sa.Text(), nullable=True),
    sa.Column('suggested_sort', sa.Text(), nullable=True),
    sa.Column('banned_at_utc', sa.Text(), nullable=True),
    sa.Column('url_overridden_by_dest', sa.Text(), nullable=True),
    sa.Column('view_count', sa.Text(), nullable=True),
    sa.Column('archived', sa.Boolean(), nullable=True),
    sa.Column('is_crosspostable', sa.Boolean(), nullable=True),
    sa.Column('pinned', sa.Boolean(), nullable=True),
    sa.Column('over_18', sa.Boolean(), nullable=True),
    sa.Column('media_only', sa.Boolean(), nullable=True),
    sa.Column('can_gild', sa.Boolean(), nullable=True),
    sa.Column('spoiler', sa.Boolean(), nullable=True),
    sa.Column('locked', sa.Boolean(), nullable=True),
    sa.Column('author_flair_text', sa.Text(), nullable=True),
    sa.Column('visited', sa.Boolean(), nullable=True),
    sa.Column('removed_by', sa.Text(), nullable=True),
    sa.Column('distinguished', sa.Text(), nullable=True),
    sa.Column('mod_reason_by', sa.Text(), nullable=True),
    sa.Column('removal_reason', sa.Text(), nullable=True),
    sa.Column('link_flair_background_color', sa.Text(), nullable=True),
    sa.Column('is_robot_indexable', sa.Boolean(), nullable=True),
    sa.Column('report_reasons', sa.Text(), nullable=True),
    sa.Column('discussion_type', sa.Text(), nullable=True),
    sa.Column('send_replies', sa.Boolean(), nullable=True),
    sa.Column('whitelist_status', sa.Text(), nullable=True),
    sa.Column('contest_mode', sa.Boolean(), nullable=True),
    sa.Column('author_patreon_flair', sa.Boolean(), nullable=True),
    sa.Column('author_flair_text_color', sa.Text(), nullable=True),
    sa.Column('link_flair_template_id', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['sun_post_detail_id'], ['posts.post_versions.sun_post_detail_id'], ),
    sa.PrimaryKeyConstraint('sun_post_detail_id'),
    schema='posts'
    )
    with op.batch_alter_table('post_details', schema='posts') as batch_op:
        batch_op.create_index(batch_op.f('ix_posts_post_details_sun_post_detail_id'), ['sun_post_detail_id'], unique=False)

    op.create_table('comment_details',
    sa.Column('sun_comment_detail_id', sa.BigInteger(), nullable=False),
    sa.Column('sun_created_at', sa.DateTime(), server_default=sa.text('(now())'), nullable=False),
    sa.Column('controversiality', sa.BigInteger(), nullable=True),
    sa.Column('ups', sa.BigInteger(), nullable=True),
    sa.Column('downs', sa.BigInteger(), nullable=True),
    sa.Column('score', sa.BigInteger(), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('edited', sa.BigInteger(), nullable=True),
    sa.Column('removed', sa.Boolean(), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('author_cakeday', sa.Boolean(), nullable=True),
    sa.Column('author_has_subscribed', sa.Boolean(), nullable=True),
    sa.Column('author_is_mod', sa.Boolean(), nullable=True),
    sa.Column('comment_type', sa.Text(), nullable=True),
    sa.Column('author_flair_type', sa.Text(), nullable=True),
    sa.Column('total_awards_received', sa.BigInteger(), nullable=True),
    sa.Column('author_flair_template_id', sa.Text(), nullable=True),
    sa.Column('mod_reason_title', sa.Text(), nullable=True),
    sa.Column('gilded', sa.BigInteger(), nullable=True),
    sa.Column('archived', sa.Boolean(), nullable=True),
    sa.Column('collapsed_reason_code', sa.Text(), nullable=True),
    sa.Column('no_follow', sa.Boolean(), nullable=True),
    sa.Column('can_mod_post', sa.Boolean(), nullable=True),
    sa.Column('send_replies', sa.Boolean(), nullable=True),
    sa.Column('mod_note', sa.Text(), nullable=True),
    sa.Column('collapsed', sa.Boolean(), nullable=True),
    sa.Column('top_awarded_type', sa.Text(), nullable=True),
    sa.Column('author_flair_css_class', sa.Text(), nullable=True),
    sa.Column('author_patreon_flair', sa.Boolean(), nullable=True),
    sa.Column('body_html', sa.Text(), nullable=True),
    sa.Column('removal_reason', sa.Text(), nullable=True),
    sa.Column('collapsed_reason', sa.Text(), nullable=True),
    sa.Column('distinguished', sa.Text(), nullable=True),
    sa.Column('associated_award', sa.Text(), nullable=True),
    sa.Column('stickied', sa.Boolean(), nullable=True),
    sa.Column('author_premium', sa.Boolean(), nullable=True),
    sa.Column('can_gild', sa.Boolean(), nullable=True),
    sa.Column('unrepliable_reason', sa.Text(), nullable=True),
    sa.Column('author_flair_text_color', sa.Text(), nullable=True),
    sa.Column('score_hidden', sa.Boolean(), nullable=True),
    sa.Column('subreddit_type', sa.Text(), nullable=True),
    sa.Column('locked', sa.Boolean(), nullable=True),
    sa.Column('report_reasons', sa.Text(), nullable=True),
    sa.Column('author_flair_text', sa.Text(), nullable=True),
    sa.Column('author_flair_background_color', sa.Text(), nullable=True),
    sa.Column('collapsed_because_crowd_control', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['sun_comment_detail_id'], ['comments.comment_versions.sun_comment_detail_id'], ),
    sa.PrimaryKeyConstraint('sun_comment_detail_id'),
    schema='comments'
    )
    with op.batch_alter_table('comment_details', schema='comments') as batch_op:
        batch_op.create_index(batch_op.f('ix_comments_comment_details_sun_comment_detail_id'), ['sun_comment_detail_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment_details', schema='comments') as batch_op:
        batch_op.drop_index(batch_op.f('ix_comments_comment_details_sun_comment_detail_id'))

    op.drop_table('comment_details', schema='comments')
    with op.batch_alter_table('post_details', schema='posts') as batch_op:
        batch_op.drop_index(batch_op.f('ix_posts_post_details_sun_post_detail_id'))

    op.drop_table('post_details', schema='posts')
    with op.batch_alter_table('comment_versions', schema='comments') as batch_op:
        batch_op.drop_index('ix_comments_comment_versions')

    op.drop_table('comment_versions', schema='comments')
    with op.batch_alter_table('subreddit_details', schema='subreddits') as batch_op:
        batch_op.drop_index(batch_op.f('ix_subreddits_subreddit_details_sun_subreddit_detail_id'))

    op.drop_table('subreddit_details', schema='subreddits')
    with op.batch_alter_table('post_versions', schema='posts') as batch_op:
        batch_op.drop_index('ix_posts_post_versions')

    op.drop_table('post_versions', schema='posts')
    with op.batch_alter_table('comments', schema='comments') as batch_op:
        batch_op.drop_index(batch_op.f('ix_comments_comments_sun_comment_id'))

    op.drop_table('comments', schema='comments')
    with op.batch_alter_table('account_details', schema='accounts') as batch_op:
        batch_op.drop_index(batch_op.f('ix_accounts_account_details_sun_account_detail_id'))

    op.drop_table('account_details', schema='accounts')
    with op.batch_alter_table('subreddit_versions', schema='subreddits') as batch_op:
        batch_op.drop_index('ix_subreddits_subreddit_versions')

    op.drop_table('subreddit_versions', schema='subreddits')
    with op.batch_alter_table('posts', schema='posts') as batch_op:
        batch_op.drop_index(batch_op.f('ix_posts_posts_sun_post_id'))

    op.drop_table('posts', schema='posts')
    with op.batch_alter_table('account_versions', schema='accounts') as batch_op:
        batch_op.drop_index('ix_accounts_account_versions')

    op.drop_table('account_versions', schema='accounts')
    with op.batch_alter_table('subreddits', schema='subreddits') as batch_op:
        batch_op.drop_index(batch_op.f('ix_subreddits_subreddits_sun_subreddit_id'))

    op.drop_table('subreddits', schema='subreddits')
    with op.batch_alter_table('accounts', schema='accounts') as batch_op:
        batch_op.drop_index(batch_op.f('ix_accounts_accounts_sun_account_id'))

    op.drop_table('accounts', schema='accounts')
    # ### end Alembic commands ###
