"""add post subreddit index

Revision ID: 8b61fe3a51ce
Revises: 581822d8495e
Create Date: 2023-02-25 21:25:27.142373

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b61fe3a51ce'
down_revision = '581822d8495e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema='posts') as batch_op:
        batch_op.create_index(batch_op.f('ix_posts_posts_reddit_subreddit_id'), ['reddit_subreddit_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema='posts') as batch_op:
        batch_op.drop_index(batch_op.f('ix_posts_posts_reddit_subreddit_id'))

    # ### end Alembic commands ###
