--DROP TABLE IF EXISTS comment.comment;

-- TODO: Organize this correctly

CREATE TABLE IF EXISTS comment.comment (
	comment_id int8 NOT NULL PRIMARY KEY,
	reddit_comment_id text NULL,
	reddit_account_id text NULL,
	parent_reddit_post_id text NULL,
	reddit_post_id text NULL,
	reddit_subreddit_id text NULL,
	id text NULL,
	body text NULL,
	edited text NULL,
	gilded float8 NULL,
	created_utc float8 NULL,
	score float8 NULL,
	downs float8 NULL,
	ups float8 NULL,
	permalink text NULL,
	created float8 NULL,
	controversiality float8 NULL,
	modified_at timestamp NULL,
	created_at timestamp NOT NULL DEFAULT NOW(),
	comment_type float8 NULL,
	approved_at_utc float8 NULL,
	author_is_blocked bool NULL,
	mod_reason_by float8 NULL,
	banned_by float8 NULL,
	author_flair_type text NULL,
	total_awards_received float8 NULL,
	author_flair_template_id text NULL,
	likes float8 NULL,
	saved bool NULL,
	banned_at_utc float8 NULL,
	mod_reason_title float8 NULL,
	archived bool NULL,
	collapsed_reason_code text NULL,
	no_follow bool NULL,
	can_mod_post bool NULL,
	send_replies bool NULL,
	approved_by float8 NULL,
	mod_note float8 NULL,
	collapsed bool NULL,
	top_awarded_type float8 NULL,
	author_flair_css_class text NULL,
	is_submitter bool NULL,
	author_patreon_flair bool NULL,
	body_html text NULL,
	removal_reason float8 NULL,
	collapsed_reason float8 NULL,
	distinguished text NULL,
	associated_award float8 NULL,
	stickied bool NULL,
	author_premium bool NULL,
	can_gild bool NULL,
	unrepliable_reason float8 NULL,
	author_flair_text_color text NULL,
	score_hidden bool NULL,
	subreddit_type text NULL,
	locked bool NULL,
	report_reasons float8 NULL,
	author_flair_text text NULL,
	subreddit_name_prefixed text NULL,
	depth int8 NULL,
	author_flair_background_color text NULL,
	collapsed_because_crowd_control float8 NULL,
	num_reports float8 NULL,
	fetched bool NULL,
	count float8 NULL,
	comments float8 NULL,
	author_cakeday bool NULL
);


--DROP TABLE IF EXISTS comments.source_iterables;

CREATE TABLE IF EXISTS comments.source_iterables (
	comment_id text NULL,
	modified_at timestamp NULL,
	created_at timestamp NOT NULL DEFAULT NOW(),
	awarders text NULL,
	user_reports text NULL,
	all_awardings text NULL,
	author_flair_richtext text NULL,
	gildings text NULL,
	treatment_tags text NULL,
	mod_reports text NULL,
	children text NULL,
	media_metadata text NULL
);