--DROP SCHEMA IF EXISTS posts CASCADE;
CREATE SCHEMA IF NOT EXISTS posts;

--DROP TABLE IF EXISTS posts.posts;

CREATE TABLE IF NOT EXISTS posts.posts (
    post_id int8 NOT NULL PRIMARY KEY,
	id text NULL,
	reddit_post_id text NULL,
	reddit_account_id text NULL,
	reddit_subreddit_id text NULL,
	modified_at timestamp NOT NULL,
	created_at timestamp NOT NULL DEFAULT NOW(),
	subreddit_name_prefixed text NULL,
	title text NULL,
	gilded int8 NULL,
	selftext text NULL,
	approved_at_utc text NULL,
	downs int8 NULL,
	subreddit_type text NULL,
	ups int8 NULL,
	upvote_ratio float8 NULL,
	permalink text NULL,
	num_reports text NULL,
	comment_limit int8 NULL,
	comment_sort text NULL,
	saved bool NULL,
	mod_reason_title text NULL,
	clicked bool NULL,
	hidden bool NULL,
	pwls int8 NULL,
	link_flair_css_class text NULL,
	thumbnail_height int8 NULL,
	top_awarded_type text NULL,
	hide_score bool NULL,
	quarantine bool NULL,
	link_flair_text_color text NULL,
	author_flair_background_color text NULL,
	total_awards_received int8 NULL,
	thumbnail_width int8 NULL,
	author_flair_template_id text NULL,
	is_original_content bool NULL,
	is_reddit_media_domain bool NULL,
	is_meta bool NULL,
	category text NULL,
	link_flair_text text NULL,
	can_mod_post bool NULL,
	score int8 NULL,
	approved_by text NULL,
	is_created_from_ads_ui bool NULL,
	author_premium bool NULL,
	thumbnail text NULL,
	edited bool NULL,
	author_flair_css_class text NULL,
	post_hint text NULL,
	is_self bool NULL,
	mod_note text NULL,
	created float8 NULL,
	link_flair_type text NULL,
	wls int8 NULL,
	removed_by_category text NULL,
	banned_by text NULL,
	author_flair_type text NULL,
	"domain" text NULL,
	allow_live_comments bool NULL,
	selftext_html text NULL,
	likes text NULL,
	suggested_sort text NULL,
	banned_at_utc text NULL,
	url_overridden_by_dest text NULL,
	view_count text NULL,
	archived bool NULL,
	no_follow bool NULL,
	is_crosspostable bool NULL,
	pinned bool NULL,
	over_18 bool NULL,
	media_only bool NULL,
	can_gild bool NULL,
	spoiler bool NULL,
	"locked" bool NULL,
	author_flair_text text NULL,
	visited bool NULL,
	removed_by text NULL,
	distinguished text NULL,
	author_is_blocked bool NULL,
	mod_reason_by text NULL,
	removal_reason text NULL,
	link_flair_background_color text NULL,
	is_robot_indexable bool NULL,
	report_reasons text NULL,
	discussion_type text NULL,
	num_comments int8 NULL,
	send_replies bool NULL,
	whitelist_status text NULL,
	contest_mode bool NULL,
	author_patreon_flair bool NULL,
	author_flair_text_color text NULL,
	parent_whitelist_status text NULL,
	stickied bool NULL,
	url text NULL,
	subreddit_subscribers int8 NULL,
	created_utc float8 NULL,
	num_crossposts int8 NULL,
	is_video bool NULL,
	fetched bool NULL,
	link_flair_template_id text NULL
);

--DROP TABLE IF EXISTS posts.source_iterables;

CREATE TABLE IF NOT EXISTS posts.source_iterables (
	post_id int8 NULL PRIMARY KEY REFERENCES posts.posts(post_id);,
	modified_at timestamp NULL,
	created_at timestamp NOT NULL DEFAULT NOW(),
	link_flair_richtext text NULL,
	media_embed text NULL,
	user_reports text NULL,
	secure_media text NULL,
	secure_media_embed text NULL,
	author_flair_richtext text NULL,
	gildings text NULL,
	content_categories text NULL,
	preview text NULL,
	all_awardings text NULL,
	awarders text NULL,
	treatment_tags text NULL,
	mod_reports text NULL,
	media text NULL,
	comments_by_id text NULL
);


