DROP SCHEMA IF EXISTS subreddits CASCADE;

CREATE SCHEMA subreddits AUTHORIZATION mainuser;
-- subreddits.subreddits definition

-- Drop table

-- DROP TABLE subreddits.subreddits;

CREATE TABLE subreddits.subreddits (
	zen_subreddit_id int8 NOT NULL PRIMARY KEY,
	reddit_subreddit_id text NOT NULL,
	active_user_count int8 NULL,
	display_name_prefixed text NULL,
	accounts_active int8 NULL,
	public_traffic bool NULL,
	subscribers int8 NULL,
	url text NOT NULL,
	title text NULL,
	subreddit_type text NULL,
	suggested_comment_sort text NULL,
	zen_modified_at timestamp NULL,
	zen_created_at timestamp NOT NULL DEFAULT now(),
	display_name text NULL,
	created float8 NULL,
	allow_polls bool NULL,
	collapse_deleted_comments bool NULL,
	public_description_html text NULL,
	allow_videos bool NULL,
	lang text NULL,
	allow_discovery bool NULL,
	accept_followers bool NULL,
	created_utc float8 NULL,
	is_crosspostable_subreddit bool NULL,
	notification_level text NULL,
	should_show_media_in_comments_setting bool NULL,
	"path" text NULL,
	user_flair_background_color text NULL,
	submit_text_html text NULL,
	restrict_posting bool NULL,
	user_is_banned text NULL,
	free_form_reports bool NULL,
	wiki_enabled bool NULL,
	user_is_muted text NULL,
	user_can_flair_in_sr text NULL,
	header_img text NULL,
	allow_galleries bool NULL,
	primary_color text NULL,
	icon_img text NULL,
	quarantine bool NULL,
	hide_ads bool NULL,
	prediction_leaderboard_entry_type text NULL,
	emojis_enabled bool NULL,
	advertiser_category text NULL,
	public_description text NULL,
	comment_score_hide_mins int8 NULL,
	allow_predictions bool NULL,
	user_has_favorited text NULL,
	user_flair_template_id text NULL,
	community_icon text NULL,
	banner_background_image text NULL,
	original_content_tag_enabled bool NULL,
	community_reviewed bool NULL,
	submit_text text NULL,
	description_html text NULL,
	spoilers_enabled bool NULL,
	allow_talks bool NULL,
	user_flair_position text NULL,
	all_original_content bool NULL,
	has_menu_widget bool NULL,
	is_enrolled_in_new_modmail text NULL,
	key_color text NULL,
	can_assign_user_flair bool NULL,
	wls int8 NULL,
	show_media_preview bool NULL,
	submission_type text NULL,
	user_is_subscriber text NULL,
	allow_videogifs bool NULL,
	should_archive_posts bool NULL,
	user_flair_type text NULL,
	can_assign_link_flair bool NULL,
	accounts_active_is_fuzzed bool NULL,
	allow_prediction_contributors bool NULL,
	submit_text_label text NULL,
	link_flair_position text NULL,
	user_sr_flair_enabled text NULL,
	user_flair_enabled_in_sr bool NULL,
	allow_chat_post_creation bool NULL,
	user_sr_theme_enabled bool NULL,
	link_flair_enabled bool NULL,
	disable_contributor_requests bool NULL,
	banner_img text NULL,
	user_flair_text text NULL,
	content_category text NULL,
	banner_background_color text NULL,
	show_media bool NULL,
	user_is_moderator text NULL,
	over18 bool NULL,
	header_title text NULL,
	description text NULL,
	is_chat_post_feature_enabled bool NULL,
	submit_link_label text NULL,
	user_flair_text_color text NULL,
	restrict_commenting bool NULL,
	user_flair_css_class text NULL,
	allow_images bool NULL,
	whitelist_status text NULL,
	mobile_banner_image text NULL,
	user_is_contributor text NULL,
	allow_predictions_tournament bool NULL,
	videostream_links_count float8 NULL
);
CREATE INDEX ix_subreddits_subreddits_zen_subreddit_id ON subreddits.subreddits USING btree (zen_subreddit_id);


